language: android

android:
  components:
    - build-tools-19.1
    - android-19
    - sysimg-19
    - extra-android-support

licenses:
  - android-sdk-license-5be876d5 # new license!
  - '.*intel.+'

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb kill-server
  - adb start-server
  - adb wait-for-device
  - adb shell input keyevent 82 &

script:
  - gradlew connectedAndroidTest
